#include<LPC21XX.H>

void UART0_CONFIG(void);
void UART0_TX(unsigned char);

int main(){
	PINSEL0 |= 0X5;	//P0.0 = TxD0 & P0.1 = RxD0 " AND '|' IS USED NOT TO DISTURB OTHER PINS"
	UART0_CONFIG();
	while(1){
		UART0_TX('A');
	}
}

void UART0_CONFIG(void){
	U0LCR = 0X83;  //SELECT DLAB (FOR SELECTING BAUD RATE) WITH '8N1' DATA FRAME
	U0DLL = 97;	   //BAUD RATE LSB
	U0DLM = 0;	   //BAUD RATE MSB
	U0LCR = 0X03;  //ONLY '8N1' DATA FRAME 
}

void UART0_TX(unsigned char TxByte){
	U0THR = TxByte;	//CHARACTER ASSIGNED TO TRANSMITTING REGISTER
	while(((U0LSR >> 5)&1) == 0);  //CURSOR WILL BLOCK UNTIL FULL TRANSMITION BYTE OCCURS
}
